apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: chatbot-github-test671
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rh-ee-lyoon-dh/chatbot-github-test671:b68123456115d85e5d22c5f7f49874baafcb9b35@sha256:a1ee9a52850580b5dbf374fe9a3c6a8f2cbfa6a5b148d02ed94aad07668091f4 # use pre-built to bootstrap
          name: app-inference
